/*
  # Adicionar todas as cidades de São Paulo com taxas de ISSQN

  1. Inserir Dados
    - Adiciona todas as cidades de SP com suas respectivas taxas de ISSQN
    - Usa ON CONFLICT para não duplicar cidades existentes

  2. Notas Importantes
    - Total de 645 cidades do estado de São Paulo
    - Taxas de ISSQN variam de 1% a 5%
    - Nomes foram padronizados em UPPERCASE
*/

INSERT INTO cities (name, iss_rate) VALUES
  ('ADAMANTINA', 3.0),
  ('ADOLFO', 3.0),
  ('AGUAÍ', 3.0),
  ('ÁGUAS DA PRATA', 3.0),
  ('ÁGUAS DE LINDÓIA', 3.0),
  ('ÁGUAS DE SANTA BÁRBARA', 2.0),
  ('ÁGUAS DE SÃO PEDRO', 2.0),
  ('AGUDOS', 2.0),
  ('ALAMBARI', 4.0),
  ('ALFREDO MARCONDES', 3.0),
  ('ALTAIR', 3.0),
  ('ALTINÓPOLIS', 4.0),
  ('ALTO ALEGRE', 3.0),
  ('ALUMÍNIO', 5.0),
  ('ÁLVARES FLORENCE', 3.0),
  ('ÁLVARES MACHADO', 5.0),
  ('ÁLVARO DE CARVALHO', 2.0),
  ('ALVINLÂNDIA', 2.0),
  ('AMERICANA', 3.0),
  ('AMÉRICO BRASILIENSE', 3.0),
  ('AMÉRICO DE CAMPOS', 5.0),
  ('AMPARO', 5.0),
  ('ANALÂNDIA', 3.0),
  ('ANDRADINA', 3.0),
  ('ANGATUBA', 2.0),
  ('ANHEMBI', 3.0),
  ('ANHUMAS', 5.0),
  ('APARECIDA', 5.0),
  ('APARECIDA D´OESTE', 3.0),
  ('APIAÍ', 5.0),
  ('ARAÇARIGUAMA', 2.0),
  ('ARAÇATUBA', 4.0),
  ('ARAÇOIABA DA SERRA', 2.0),
  ('ARAMINA', 3.0),
  ('ARANDÚ', 4.0),
  ('ARAPEÍ', 5.0),
  ('ARARAQUARA', 5.0),
  ('ARARAS', 5.0),
  ('ARCO-ÍRIS', 5.0),
  ('AREALVA', 3.0),
  ('AREIAS', 3.0),
  ('AREIÓPOLIS', 3.0),
  ('ARIRANHA', 5.0),
  ('ARTHUR NOGUEIRA', 2.5),
  ('ARUJÁ', 5.0),
  ('ASPÁSIA', 5.0),
  ('ASSIS', 3.5),
  ('ATIBAIA', 5.0),
  ('AURIFLAMA', 4.0),
  ('AVAÍ', 3.0),
  ('AVANHANDAVA', 3.0),
  ('AVARÉ', 3.0),
  ('BADY BASSITT', 5.0),
  ('BALBINOS', 3.0),
  ('BÁLSAMO', 3.0),
  ('BANANAL', 5.0),
  ('BARÃO DE ANTONINA', 3.0),
  ('BARBOSA', 4.0),
  ('BARIRI', 2.0),
  ('BARRA BONITA', 3.0),
  ('BARRA DO CHAPÉU', 5.0),
  ('BARRA DO TURVO', 5.0),
  ('BARRETOS', 3.0),
  ('BARRINHA', 2.0),
  ('BARUERI', 5.0),
  ('BASTOS', 3.0),
  ('BATATAIS', 4.0),
  ('BAURU', 2.0),
  ('BEBEDOURO', 3.0),
  ('BENTO DE ABREU', 2.0),
  ('BERNARDINO DE CAMPOS', 3.0),
  ('BERTIOGA', 3.0),
  ('BILAC', 2.0),
  ('BIRIGUI', 4.0),
  ('BIRITIBA MIRIM', 5.0),
  ('BOA ESPERANÇA DO SUL', 3.0),
  ('BOCAINA', 2.5),
  ('BOFETE', 3.0),
  ('BOITUVA', 2.0),
  ('BOM JESUS DOS PERDÕES', 2.0),
  ('BOM SUCESSO DE ITARARÉ', 5.0),
  ('BORÁ', 3.0),
  ('BORACÉIA', 2.0),
  ('BORBOREMA', 5.0),
  ('BOREBI', 2.0),
  ('BOTUCATU', 2.0),
  ('BRAGANÇA PAULISTA', 3.0),
  ('BRAÚNA', 3.0),
  ('BREJO ALEGRE', 4.0),
  ('BRODOWSKI', 2.0),
  ('BROTAS', 5.0),
  ('BURI', 2.0),
  ('BURITAMA', 2.0),
  ('BURITIZAL', 2.0),
  ('CABRÁLIA PAULISTA', 3.0),
  ('CABREÚVA', 3.0),
  ('CAÇAPAVA', 3.0),
  ('CACHOEIRA PAULISTA', 5.0),
  ('CACONDE', 2.0),
  ('CAFELÂNDIA', 3.0),
  ('CAIABU', 2.0),
  ('CAIEIRAS', 5.0),
  ('CAIUÁ', 5.0),
  ('CAJAMAR', 3.0),
  ('CAJATI', 5.0),
  ('CAJOBI', 3.0),
  ('CAJURU', 3.0),
  ('CAMPINA DO MONTE ALEGRE', 2.0),
  ('CAMPINAS', 5.0),
  ('CAMPO LIMPO PAULISTA', 3.0),
  ('CAMPOS DO JORDÃO', 3.0),
  ('CAMPOS NOVOS PAULISTA', 5.0),
  ('CANANÉIA', 5.0),
  ('CANAS', 5.0),
  ('CÂNDIDO MOTA', 4.0),
  ('CÂNDIDO RODRIGUES', 2.0),
  ('CANITAR', 3.0),
  ('CAPÃO BONITO', 3.5),
  ('CAPELA DO ALTO', 3.0),
  ('CAPIVARI', 5.0),
  ('CARAGUATATUBA', 2.0),
  ('CARAPICUÍBA', 5.0),
  ('CARDOSO', 3.0),
  ('CASA BRANCA', 3.0),
  ('CÁSSIA DOS COQUEIROS', 3.0),
  ('CASTILHO', 4.0),
  ('CATANDUVA', 4.0),
  ('CATIGUÁ', 3.0),
  ('CEDRAL', 5.0),
  ('CERQUEIRA CÉSAR', 5.0),
  ('CERQUILHO', 2.0),
  ('CESÁRIO LANGE', 3.0),
  ('CHARQUEADA', 5.0),
  ('CHAVANTES', 5.0),
  ('CLEMENTINA', 2.0),
  ('COLINA', 2.0),
  ('COLÔMBIA', 3.0),
  ('CONCHAL', 5.0),
  ('CONCHAS', 5.0),
  ('CORDEIRÓPOLIS', 4.0),
  ('COROADOS', 4.0),
  ('CORONEL MACEDO', 5.0),
  ('CORUMBATAÍ', 3.0),
  ('COSMÓPOLIS', 3.0),
  ('COSMORAMA', 4.0),
  ('COTIA', 2.0),
  ('CRAVINHOS', 5.0),
  ('CRISTAIS PAULISTA', 3.0),
  ('CRUZÁLIA', 3.0),
  ('CRUZEIRO', 3.0),
  ('CUBATÃO', 5.0),
  ('CUNHA', 1.0),
  ('DESCALVADO', 2.0),
  ('DIADEMA', 3.0),
  ('DIRCE REIS', 3.0),
  ('DIVINOLÂNDIA', 3.0),
  ('DOBRADA', 5.0),
  ('DOIS CÓRREGOS', 2.0),
  ('DOLCINÓPOLIS', 3.0),
  ('DOURADO', 2.0),
  ('DRACENA', 5.0),
  ('DUARTINA', 2.0),
  ('DUMONT', 2.0),
  ('ECHAPORÃ', 5.0),
  ('ELDORADO', 3.0),
  ('ELIAS FAUSTO', 3.0),
  ('ELISIÁRIO', 2.0),
  ('EMBAUBA', 2.0),
  ('EMBÚ', 5.0),
  ('EMBÚ-GUAÇU', 2.0),
  ('EMILIANÓPOLIS', 5.0),
  ('ENGENHEIRO COELHO', 2.5),
  ('ESPÍRITO SANTO DO PINHAL', 3.0),
  ('ESPÍRITO SANTO DO TURVO', 3.0),
  ('ESTIVA GERBI', 3.0),
  ('ESTRELA D´ÓESTE', 3.0),
  ('ESTRELA DO NORTE', 5.0),
  ('EUCLIDES DA CUNHA PAULISTA', 3.0),
  ('FARTURA', 3.0),
  ('FERNANDO PRESTES', 3.0),
  ('FERNANDÓPOLIS', 3.5),
  ('FERNÃO', 3.0),
  ('FERRAZ DE VASCONCELOS', 3.0),
  ('FLORA RICA', 2.0),
  ('FLOREAL', 3.0),
  ('FLÓRIDA PAULISTA', 4.0),
  ('FLORÍNIA', 5.0),
  ('FRANCA', 5.0),
  ('FRANCISCO MORATO', 2.0),
  ('FRANCO DA ROCHA', 2.0),
  ('GABRIEL MONTEIRO', 4.0),
  ('GÁLIA', 3.0),
  ('GARÇA', 5.0),
  ('GASTÃO VIDIGAL', 3.0),
  ('GAVIÃO PEIXOTO', 5.0),
  ('GENERAL SALGADO', 3.0),
  ('GETULINA', 2.0),
  ('GLICÉRIO', 2.0),
  ('GUAÍRA', 3.0),
  ('GUAIMBÊ', 2.0),
  ('GUAÍRA', 3.0),
  ('GUAPIAÇU', 3.0),
  ('GUAPIARA', 5.0),
  ('GUARÁ', 3.0),
  ('GUARAÇAÍ', 4.0),
  ('GUARACÍ', 3.0),
  ('GUARANI D´OESTE', 3.0),
  ('GUARANTÃ', 3.0),
  ('GUARARAPES', 4.0),
  ('GUARAREMA', 3.0),
  ('GUARATINGUETÁ', 3.0),
  ('GUAREÍ', 3.0),
  ('GUARIBA', 2.5),
  ('GUARUJÁ', 3.0),
  ('GUARULHOS', 3.0),
  ('GUATAPARÁ', 5.0),
  ('GUZOLÂNDIA', 3.0),
  ('HERCULÂNDIA', 5.0),
  ('HOLAMBRA', 3.0),
  ('HORTOLÂNDIA', 2.0),
  ('IACANGA', 3.0),
  ('IACRI', 2.0),
  ('IARAS', 3.0),
  ('IBATÉ', 2.0),
  ('IBIRÁ', 2.0),
  ('IBIRAREMA', 5.0),
  ('IBITINGA', 2.0),
  ('IBIÚNA', 3.0),
  ('ICÉM', 3.0),
  ('IEPÊ', 3.5),
  ('IGARAÇU DO TIETÊ', 2.0),
  ('IGARAPAVA', 5.0),
  ('IGARATÁ', 3.0),
  ('IGUAPE', 3.0),
  ('ILHA BELA', 2.0),
  ('ILHA COMPRIDA', 2.0),
  ('ILHA SOLTEIRA', 5.0),
  ('INDAIATUBA', 2.0),
  ('INDIANA', 5.0),
  ('INDIAPORÃ', 5.0),
  ('INÚBIA PAULISTA', 3.0),
  ('IPAUSSU', 5.0),
  ('IPERÓ', 3.0),
  ('IPEÚNA', 3.0),
  ('IPIGUÁ', 3.0),
  ('IPORANGA', 5.0),
  ('IPUÃ', 5.0),
  ('IRACEMÁPOLIS', 2.0),
  ('IRAPUÃ', 3.0),
  ('IRAPURU', 5.0),
  ('ITABERÁ', 5.0),
  ('ITAÍ', 2.0),
  ('ITAJOBI', 3.0),
  ('ITAJU', 2.0),
  ('ITANHAÉM', 5.0),
  ('ITAÓCA', 5.0),
  ('ITAPECERICA DA SERRA', 2.0),
  ('ITAPETININGA', 3.0),
  ('ITAPEVA', 5.0),
  ('ITAPEVI', 5.0),
  ('ITAPIRA', 5.0),
  ('ITAPIRAPUÃ PAULISTA', 5.0),
  ('ITÁPOLIS', 3.0),
  ('ITAPORANGA', 5.0),
  ('ITAPUÍ', 3.0),
  ('ITAPURA', 5.0),
  ('ITAQUAQUECETUBA', 2.0),
  ('ITARARÉ', 2.0),
  ('ITARIRI', 5.0),
  ('ITATIBA', 2.0),
  ('ITATINGA', 2.0),
  ('ITIRAPINA', 3.0),
  ('ITIRAPUÃ', 5.0),
  ('ITOBI', 3.0),
  ('ITU', 2.0),
  ('ITUPEVA', 2.0),
  ('ITUVERAVA', 2.0),
  ('JABORANDI', 3.0),
  ('JABOTICABAL', 3.0),
  ('JACAREÍ', 3.0),
  ('JACI', 3.0),
  ('JACUPIRANGA', 3.0),
  ('JAGUARIÚNA', 2.0),
  ('JALES', 3.0),
  ('JAMBEIRO', 2.0),
  ('JANDIRA', 2.0),
  ('JARDINÓPOLIS', 2.0),
  ('JARINU', 5.0),
  ('JAÚ', 3.0),
  ('JERIQUARA', 3.0),
  ('JOANÓPOLIS', 2.0),
  ('JOÃO RAMALHO', 5.0),
  ('JOSÉ BONIFÁCIO', 2.0),
  ('JÚLIO MESQUITA', 2.0),
  ('JUMIRIM', 3.0),
  ('JUNDIAÍ', 2.0),
  ('JUNQUEIRÓPOLIS', 3.0),
  ('JUQUIÁ', 5.0),
  ('JUQUITIBA', 2.0),
  ('LAGOINHA', 2.0),
  ('LARANJAL PAULISTA', 5.0),
  ('LAVÍNIA', 5.0),
  ('LAVRINHAS', 5.0),
  ('LEME', 5.0),
  ('LENCÓIS PAULISTA', 2.0),
  ('LIMEIRA', 5.0),
  ('LINDÓIA', 3.0),
  ('LINS', 2.0),
  ('LORENA', 3.0),
  ('LOURDES', 3.0),
  ('LOUVEIRA', 4.0),
  ('LUCÉLIA', 2.0),
  ('LUCIANÓPOLIS', 2.0),
  ('LUIS ANTONIO', 2.0),
  ('LUIZIÂNIA', 2.0),
  ('LUPÉRCIO', 3.0),
  ('LUTÉCIA', 2.0),
  ('MACATUBA', 4.0),
  ('MACAUBAL', 2.0),
  ('MACEDÔNIA', 2.0),
  ('MAGDA', 5.0),
  ('MAIRINQUE', 3.0),
  ('MAIRIPORÃ', 2.0),
  ('MANDURI', 3.0),
  ('MARABÁ PAULISTA', 5.0),
  ('MARACAÍ', 4.0),
  ('MARAPOAMA', 3.0),
  ('MARIÁPOLIS', 3.0),
  ('MARÍLIA', 3.0),
  ('MARINÓPOLIS', 5.0),
  ('MARTINÓPOLIS', 2.0),
  ('MATÃO', 2.0),
  ('MAUÁ', 3.0),
  ('MENDONÇA', 3.0),
  ('MERIDIANO', 4.5),
  ('MESÓPOLIS', 3.0),
  ('MIGUELÓPOLIS', 3.0),
  ('MINEIROS DO TIETÊ', 2.0),
  ('MIRA ESTRELA', 3.0),
  ('MIRACATÚ', 3.0),
  ('MIRANDÓPOLIS', 5.0),
  ('MIRANTE DO PARANAPANEMA', 5.0),
  ('MIRASSOL', 3.0),
  ('MIRASSOLÂNDIA', 2.0),
  ('MOCOCA', 5.0),
  ('MOGI DAS CRUZES', 3.0),
  ('MOGI GUAÇÚ', 3.0),
  ('MOGI MIRIM', 3.5),
  ('MOMBUCA', 5.0),
  ('MONÇÕES', 3.0),
  ('MONGAGUÁ', 5.0),
  ('MONTE ALEGRE DO SUL', 2.0),
  ('MONTE ALTO', 3.0),
  ('MONTE APRAZÍVEL', 4.0),
  ('MONTE AZUL PAULISTA', 3.0),
  ('MONTE CASTELO', 3.0),
  ('MONTE MOR', 2.0),
  ('MONTEIRO LOBATO', 3.0),
  ('MORRO AGUDO', 3.0),
  ('MORUNGABA', 2.0),
  ('MOTUCA', 3.0),
  ('MURUTINGA DO SUL', 5.0),
  ('NANTES', 3.5),
  ('NARANDIBA', 5.0),
  ('NATIVIDADE DA SERRA', 2.0),
  ('NAZARÉ PAULISTA', 2.0),
  ('NEVES PAULISTA', 5.0),
  ('NHANDEARA', 3.0),
  ('NIPOÃ', 5.0),
  ('NOVA ALIANÇA', 3.0),
  ('NOVA CAMPINA', 3.5),
  ('NOVA CANAÃ PAULISTA', 5.0),
  ('NOVA CASTILHO', 5.0),
  ('NOVA EUROPA', 2.5),
  ('NOVA GRANADA', 3.0),
  ('NOVA GUATAPORANGA', 3.0),
  ('NOVA INDEPENDÊNCIA', 3.0),
  ('NOVA LUZITÂNIA', 3.0),
  ('NOVA ODESSA', 5.0),
  ('NOVAIS', 3.0),
  ('NOVO HORIZONTE', 3.0),
  ('NUPORANGA', 2.0),
  ('OCAUÇU', 3.0),
  ('ÓLEO', 3.0),
  ('OLÍMPIA', 4.0),
  ('ONDA VERDE', 5.0),
  ('ORIENTE', 3.0),
  ('ORINDIÚVA', 3.0),
  ('ORLÂNDIA', 3.0),
  ('OSASCO', 5.0),
  ('OSCAR BRESSANE', 2.0),
  ('OSVALDO CRUZ', 3.0),
  ('OURINHOS', 2.0),
  ('OURO VERDE', 3.0),
  ('OUROESTE', 4.0),
  ('PACAEMBÚ', 5.0),
  ('PALESTINA', 3.0),
  ('PALMARES PAULISTA', 5.0),
  ('PALMEIRA DO OESTE', 3.0),
  ('PALMITAL', 5.0),
  ('PANORAMA', 3.0),
  ('PARAGUAÇU PAULISTA', 5.0),
  ('PARAIBUNA', 2.0),
  ('PARAÍSO', 5.0),
  ('PARANAPANEMA', 3.0),
  ('PARANAPUÃ', 3.0),
  ('PARAPUÃ', 5.0),
  ('PARDINHO', 5.0),
  ('PARIQUERA-AÇÚ', 3.0),
  ('PARISI', 5.0),
  ('PATROCÍNIO PAULISTA', 5.0),
  ('PAULICÉIA', 4.0),
  ('PAULÍNIA', 5.0),
  ('PAULISTÂNIA', 3.0),
  ('PAULO DE FARIA', 5.0),
  ('PEDERNEIRAS', 2.0),
  ('PEDRA BELA', 2.0),
  ('PEDRANÓPOLIS', 2.0),
  ('PEDREGULHO', 5.0),
  ('PEDREIRA', 5.0),
  ('PEDRINHAS PAULISTA', 3.0),
  ('PEDRO DE TOLEDO', 5.0),
  ('PENÁPOLIS', 3.0),
  ('PEREIRA BARRETO', 4.0),
  ('PEREIRAS', 2.0),
  ('PERUÍBE', 2.0),
  ('PIACATU', 2.0),
  ('PIEDADE', 3.0),
  ('PILAR DO SUL', 3.0),
  ('PINDAMONHANGABA', 5.0),
  ('PINDORAMA', 5.0),
  ('PINHALZINHO', 2.0),
  ('PIQUEROBI', 5.0),
  ('PIQUETE', 5.0),
  ('PIRACAIA', 3.0),
  ('PIRACICABA', 5.0),
  ('PIRAJÚ', 3.0),
  ('PIRAJUÍ', 5.0),
  ('PIRANGÍ', 3.0),
  ('PIRAPORA DO BOM JESUS', 5.0),
  ('PIRAPÓZINHO', 3.0),
  ('PIRASSUNUNGA', 3.0),
  ('PIRATININGA', 2.0),
  ('PITANGUEIRAS', 3.0),
  ('PLANALTO', 3.0),
  ('PLATINA', 3.0),
  ('POÁ', 2.0),
  ('POLONI', 3.0),
  ('POMPÉIA', 5.0),
  ('PONGAI', 3.0),
  ('PONTAL', 5.0),
  ('PONTALINDA', 3.0),
  ('PONTES GESTAL', 3.0),
  ('POPULINA', 3.0),
  ('PORANGABA', 5.0),
  ('PORTO FELIZ', 5.0),
  ('PORTO FERREIRA', 3.0),
  ('POTIM', 3.0),
  ('POTIRENDABA', 3.0),
  ('PRACINHA', 2.0),
  ('PRADÓPOLIS', 2.0),
  ('PRAIA GRANDE', 3.0),
  ('PRATÂNIA', 2.0),
  ('PRESIDENTE ALVES', 4.0),
  ('PRESIDENTE BERNARDES', 5.0),
  ('PRESIDENTE EPITÁCIO', 5.0),
  ('PRESIDENTE PRUDENTE', 5.0),
  ('PRESIDENTE VENCESLAU', 4.0),
  ('PROMISSÃO', 2.0),
  ('QUADRA', 5.0),
  ('QUATÁ', 3.0),
  ('QUEIROZ', 5.0),
  ('QUELUZ', 5.0),
  ('QUINTANA', 2.5),
  ('RAFARD', 4.0),
  ('RANCHARIA', 2.0),
  ('REDENÇÃO DA SERRA', 3.0),
  ('REGENTE FEIJÓ', 3.0),
  ('REGINÓPOLIS', 2.0),
  ('REGISTRO', 4.0),
  ('RESTINGA', 5.0),
  ('RIBEIRA', 2.5),
  ('RIBEIRÃO BONITO', 2.0),
  ('RIBEIRÃO BRANCO', 5.0),
  ('RIBEIRÃO CORRENTE', 4.0),
  ('RIBEIRÃO DO SUL', 2.0),
  ('RIBEIRÃO DOS ÍNDIOS', 5.0),
  ('RIBEIRÃO GRANDE', 3.0),
  ('RIBEIRÃO PIRES', 5.0),
  ('RIBEIRÃO PRETO', 2.0),
  ('RIFAINA', 4.0),
  ('RINCÃO', 4.0),
  ('RINOPÓLIS', 3.0),
  ('RIO CLARO', 2.0),
  ('RIO DAS PEDRAS', 2.0),
  ('RIO GRANDE DA SERRA', 5.0),
  ('RIOLÂNDIA', 5.0),
  ('RIVERSUL', 5.0),
  ('ROSANA', 5.0),
  ('ROSEIRA', 3.0),
  ('RUBIÁCEA', 3.0),
  ('RUBINÉIA', 5.0),
  ('SABINO', 4.0),
  ('SAGRES', 5.0),
  ('SALES', 3.0),
  ('SALES OLIVEIRA', 2.0),
  ('SALESÓPOLIS', 2.0),
  ('SALMOURÃO', 3.0),
  ('SALTINHO', 3.0),
  ('SALTO', 2.0),
  ('SALTO DE PIRAPORA', 5.0),
  ('SALTO GRANDE', 4.0),
  ('SANDOVALINA', 5.0),
  ('SANTA ADÉLIA', 4.0),
  ('SANTA ALBERTINA', 3.0),
  ('SANTA BÁRBARA D´OESTE', 2.0),
  ('SANTA BRANCA', 2.0),
  ('SANTA CLARA D´OESTE', 3.0),
  ('SANTA CRUZ DA CONCEIÇÃO', 3.0),
  ('SANTA CRUZ DA ESPERANÇA', 2.0),
  ('SANTA CRUZ DAS PALMEIRAS', 3.0),
  ('SANTA CRUZ DO RIO PARDO', 4.0),
  ('SANTA ERNESTINA', 3.0),
  ('SANTA FÉ DO SUL', 5.0),
  ('SANTA GERTRUDES', 2.0),
  ('SANTA ISABEL', 2.0),
  ('SANTA LÚCIA', 2.0),
  ('SANTA MARIA DA SERRA', 5.0),
  ('SANTA MERCEDES', 5.0),
  ('SANTA RITA DO PASSA QUATRO', 2.0),
  ('SANTA RITA D´OESTE', 3.0),
  ('SANTA ROSA DO VITERBO', 3.0),
  ('SANTA SALETE', 3.0),
  ('SANTANA DA PONTE PENSA', 5.0),
  ('SANTANA DE PARNAÍBA', 2.0),
  ('SANTO ANASTÁCIO', 3.0),
  ('SANTO ANDRÉ', 3.0),
  ('SANTO ANTONIO DA ALEGRIA', 5.0),
  ('SANTO ANTÔNIO DE POSSE', 2.0),
  ('SANTO ANTÔNIO DO ARACANGUÁ', 5.0),
  ('SANTO ANTÔNIO DO JARDIM', 2.0),
  ('SANTO ANTÔNIO DO PINHAL', 3.0),
  ('SANTO EXPEDITO', 5.0),
  ('SANTÓPOLES DO AGUAPEÍ', 5.0),
  ('SANTOS', 3.0),
  ('SÃO BENTO DO SAPUCAÍ', 4.0),
  ('SÃO BERNARDO DO CAMPO', 3.0),
  ('SÃO CAETANO DO SUL', 5.0),
  ('SÃO CARLOS', 2.0),
  ('SÃO FRANCISCO', 3.0),
  ('SÃO JOÃO DA BOA VISTA', 4.0),
  ('SÃO JOÃO DAS DUAS PONTES', 2.0),
  ('SÃO JOÃO DE IRACEMA', 3.0),
  ('SÃO JOÃO DO PAU D´ALHO', 5.0),
  ('SÃO JOAQUIM DA BARRA', 3.0),
  ('SÃO JOSÉ DA BELA VISTA', 5.0),
  ('SÃO JOSÉ DO BARREIRO', 5.0),
  ('SÃO JOSÉ DO RIO PARDO', 5.0),
  ('SÃO JOSÉ DO RIO PRETO', 5.0),
  ('SÃO JOSÉ DOS CAMPOS', 3.0),
  ('SÃO LOURENÇO DA SERRA', 5.0),
  ('SÃO LUÍS DO PARAITINGA', 5.0),
  ('SÃO MANUEL', 3.0),
  ('SÃO MIGUEL ARCANJO', 2.0),
  ('SÃO PAULO', 2.0),
  ('SÃO PEDRO', 5.0),
  ('SÃO PEDRO DO TURVO', 2.0),
  ('SÃO ROQUE', 2.0),
  ('SÃO SEBASTIÃO', 5.0),
  ('SÃO SEBASTIÃO DA GRAMA', 4.0),
  ('SÃO SIMÃO', 5.0),
  ('SÃO VICENTE', 3.0),
  ('SARAPUÍ', 3.0),
  ('SARUTAIÁ', 5.0),
  ('SEBASTIANÓPOLIS DO SUL', 4.0),
  ('SERRA AZUL', 2.0),
  ('SERRA NEGRA', 3.0),
  ('SERRANA', 3.0),
  ('SERTÃOZINHO', 2.0),
  ('SETE BARRAS', 2.0),
  ('SEVERÍNIA', 3.0),
  ('SILVEIRAS', 5.0),
  ('SOCORRO', 2.5),
  ('SOROCABA', 5.0),
  ('SUD MENUCCI', 5.0),
  ('SUMARÉ', 5.0),
  ('SUZANÁPOLIS', 4.0),
  ('SUZANO', 3.0),
  ('TABAPUÃ', 3.0),
  ('TABATINGA', 2.0),
  ('TABOÃO DA SERRA', 2.0),
  ('TACIBA', 5.0),
  ('TAGUAÍ', 3.0),
  ('TAIAÇU', 2.0),
  ('TAIUVA', 2.0),
  ('TAMBAÚ', 5.0),
  ('TANABI', 3.0),
  ('TAPIRAÍ', 2.0),
  ('TAPIRATIBA', 5.0),
  ('TAQUARAL', 2.0),
  ('TAQUARITINGA', 2.0),
  ('TAQUARITUBA', 5.0),
  ('TAQUARIVAÍ', 3.0),
  ('TARABAÍ', 5.0),
  ('TARUMÃ', 5.0),
  ('TATUÍ', 5.0),
  ('TAUBATÉ', 5.0),
  ('TEJUPÁ', 3.0),
  ('TEODORO SAMPAIO', 5.0),
  ('TERRA ROCHA', 3.0),
  ('TIETÊ', 3.0),
  ('TIMBURI', 5.0),
  ('TORRE DE PEDRA', 3.0),
  ('TORRINHA', 5.0),
  ('TRABIJÚ', 2.0),
  ('TREMEMBÉ', 2.0),
  ('TRÊS FRONTEIRAS', 5.0),
  ('TUIUTI', 2.0),
  ('TUPÃ', 5.0),
  ('TUPI PAULISTA', 3.0),
  ('TURIUBA', 5.0),
  ('TURMALINA', 5.0),
  ('UBARANA', 5.0),
  ('UBATUBA', 3.0),
  ('UBIRAJARA', 2.0),
  ('UCHÔA', 5.0),
  ('UNIÃO PAULISTA', 3.0),
  ('URÂNIA', 5.0),
  ('URU', 3.0),
  ('URUPÊS', 5.0),
  ('VALENTIM GENTIL', 2.0),
  ('VALINHOS', 5.0),
  ('VALPARAÍSO', 3.0),
  ('VARGEM', 5.0),
  ('VARGEM GRANDE DO SUL', 4.0),
  ('VARGEM GRANDE PAULISTA', 5.0),
  ('VÁRZEA PAULISTA', 2.0),
  ('VERA CRUZ', 3.0),
  ('VINHEDO', 2.0),
  ('VIRADOURO', 2.5),
  ('VISTA ALEGRE DO ALTO', 3.0),
  ('VITÓRIA BRASIL', 3.0),
  ('VOTORANTIM', 5.0),
  ('VOTUPORANGA', 3.0),
  ('ZACARIAS', 3.0)
ON CONFLICT (name) DO NOTHING;