-- Marketing: Solicitações (tickets)
-- Data: 2026-02-20

-- Necessário para gen_random_uuid()
create extension if not exists pgcrypto;

create table if not exists public.marketing_solicitacoes (
  id uuid primary key default gen_random_uuid(),

  solicitacao_numero bigint generated by default as identity,

  titulo text not null,
  tipo text not null,
  departamento text not null,
  prioridade text not null,
  pontos int null,
  descricao text not null,

  status text not null default 'A fazer',

  solicitante_nome text not null,
  solicitante_email text not null,

  data_abertura timestamptz not null default now(),
  data_inicio timestamptz null,
  data_conclusao timestamptz null,

  historico jsonb not null default '[]'::jsonb,

  arquivado boolean not null default false,
  data_arquivamento timestamptz null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists marketing_solicitacoes_numero_uq
  on public.marketing_solicitacoes (solicitacao_numero);

create index if not exists marketing_solicitacoes_status_idx
  on public.marketing_solicitacoes (status);

create index if not exists marketing_solicitacoes_arquivado_idx
  on public.marketing_solicitacoes (arquivado);

-- Controle simples de quem pode gerenciar (mover status/editar/arquivar)
do $$
begin
  if to_regclass('public.app_users') is not null then
    execute $sql$
      create table if not exists public.marketing_roles (
        id uuid primary key default gen_random_uuid(),
        app_user_id uuid not null references public.app_users(id) on delete cascade,
        role text not null default 'editor',
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        constraint marketing_roles_role_chk check (role in ('editor')),
        constraint marketing_roles_app_user_uq unique (app_user_id)
      );
    $sql$;
  else
    -- Alguns ambientes podem ainda não ter a tabela public.app_users.
    -- Nesse caso, criamos a tabela sem FK para permitir executar a migration.
    execute $sql$
      create table if not exists public.marketing_roles (
        id uuid primary key default gen_random_uuid(),
        app_user_id uuid not null,
        role text not null default 'editor',
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        constraint marketing_roles_role_chk check (role in ('editor')),
        constraint marketing_roles_app_user_uq unique (app_user_id)
      );
    $sql$;
  end if;
end $$;

-- Observação:
-- Este app atualmente usa credenciais anon no client e uma tabela de login própria (app_users).
-- Se você habilitar RLS para essas tabelas, precisará criar políticas compatíveis com o seu modelo de auth.
